theme: jekyll-theme-cayman
title: Troubleshoot apps with RUM
description: Written by Anastasiya Maliborskaya (Selivanava) for Dynatrace as part of the technical writing assignment.
google_analytics: G-3PV7Y0HMVE
